// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transactions": {
            "post": {
                "description": "Calculates commission and fees, saves to DB, and returns the created transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a new transaction",
                "parameters": [
                    {
                        "description": "Transaction Request",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler.createTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_CardenalDex_crudprotec_internal_entitys.Transaction"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_CardenalDex_crudprotec_internal_entitys.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Value in cents (200.00 -\u003e 20000)",
                    "type": "integer",
                    "format": "int64"
                },
                "commission": {
                    "description": "in cents",
                    "type": "integer",
                    "format": "int64"
                },
                "deletedAt": {
                    "type": "string"
                },
                "fee": {
                    "description": "in centi% 5.5=550",
                    "type": "integer",
                    "format": "int64"
                },
                "id": {
                    "type": "string"
                },
                "merchantID": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler.createTransactionRequest": {
            "type": "object",
            "required": [
                "amount",
                "merchant_id"
            ],
            "properties": {
                "amount": {
                    "description": "Input as float for user friendliness",
                    "type": "number"
                },
                "merchant_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Payment System API",
	Description:      "Clean Architecture Example with Go, Docker.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
